### ISSUE TITLE
Manifestation Titlepage generates temporary wrapper paragraphs

### ISSUE THREAD

**Issue by dikastes** [Edirom/MerMEId#169] opened 2023-07-06 15:02 UTC
After setting a titlepage of a manifestation and saving, the manifestation/physDesc/titlePage element contains a paragraph element with attribute n="MerMEId_temporary_wrapper". On some installations (not all, though), saving a document containing that paragraph element fails with this error message:

Submission response status: 500 Error type: resource-error URI: http://127.0.0.2:8080/apps/mermeid/data/festklaenge-copy.xml Headers: Date Thu, 06 Jul 2023 11:34:47 GMT

**Comment by peterstadler** [comment] 2023-10-12 12:43
maybe related to #90

**Comment by peterstadler** [comment] 2023-11-15 16:50
We could not reproduce the issue during our sprint today.
But what we discovered concerning the "MerMEId_temporary_wrapper" paragraphs is
* those markers are correctly removed from the XML through `filter_put.xsl`
* the XML view (accessed through the XForms top nav) had shown an unfiltered version, see #177

Hence, this suggests the error 500 is *not* originating from the "MerMEId_temporary_wrapper" itself although it might be related to the processing with `filter_put.xsl`. 

Yet, since we were not able to reproduce the issue we're closing the issue for now but please feel free to reopen! In that case, the MerMEId version and the exact steps for reproducing the issue would be helpful.

**Closed by peterstadler** 2023-11-15 16:50 UTC
Labels: bug
